CREATE TABLE Vendeg_Mask
(
  USERNEV VARCHAR(20),
  NEV VARCHAR(50) MASKED WITH (FUNCTION = 'partial(1,"XXXXXX",0)'),
  EMAIL VARCHAR(60) MASKED WITH (FUNCTION = 'email()'),
  SZAML_CIM VARCHAR(100) MASKED WITH (FUNCTION = 'partial(5,"XXXXXXX",0)'),
  SZUL_DAT [date] NULL
);